name: Build and test
on: [push, pull_request]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run dist
      - name: Run test
        run: npm test
